apiVersion: v1
kind: Service
metadata:
  name: hotstuff-exporter
  namespace: apps
  labels:
    app: hotstuff-controller
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9108"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: hotstuff-controller
  ports:
    - name: metrics
      port: 9108
      targetPort: 9108
      protocol: TCP
  type: ClusterIP
