apiVersion: v1
kind: Service
metadata:
  name: hotstuff-controller
spec:
  selector:
    app: hotstuff-controller
  ports:
    - protocol: TCP
      port: 8080         
      targetPort: 8080   
  type: ClusterIP 
