name: CI/CD with Docker


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push controller image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/Dockerfile.controller
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hotstuff-controller:latest
            ${{ secrets.DOCKER_USERNAME }}/hotstuff-controller:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=gha
          
      - name: Build and push worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/Dockerfile.worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hotstuff-worker:latest
            ${{ secrets.DOCKER_USERNAME }}/hotstuff-worker:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=gha
